version: '3.1'

services:
  db:
    container_name: fso-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 'Password!'
    ports:
      - 1444:1433
    volumes:
      - fso-db-data:/var/opt/mssql

  # cache:
  #   container_name: fso-cache
  #   hostname: valkey
  #   image: valkey/valkey:7.2.5
  #   volumes:
  #     - ./config/valkey.conf:/etc/valkey/valkey.conf
  #     # - fso-cache-data:/data
  #   command: valkey-server /etc/valkey/valkey.conf
  #   ports:
  #     - 6380:6379
  # query-cache:
  #   container_name: fso-query-cache
  #   hostname: valkey
  #   image: valkey/valkey:7.2.5
  #   volumes:
  #     - ./config/valkey.conf:/etc/valkey/valkey.conf
  #     # - fso-cache-data:/data
  #   command: valkey-server /etc/valkey/valkey.conf
  #   ports:
  #     - 6381:6379

volumes:
  fso-db-data:
