version: '3.1'

services:
  db: # TODO rename to card-db
    container_name: fso-db # TODO rename to fso-card-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # - .:/docker-entrypoint-initdb.d
      - fso-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # message-broker:
  #   image: rabbitmq:3-management-alpine
  #   container_name: fso-messages
  #   ports:
  #     - 5672:5672
  #     - 15672:15672 # web UI
  # logs-visualizer:
  #   container_name: fso-logs-visualizer
  #   image: grafana/grafana-oss
  #   ports:
  #     - 3000:3000
  # time-db:
  #   image: influxdb:2
  #   container_name: fso-time-db
  #   ports:
  #     - 8086:8086
  #   volumes:
  #     - time-db-data:/var/lib/influxdb2

  # cache:
  #   container_name: fso-cache
  #   hostname: valkey
  #   image: valkey/valkey:7.2.5
  #   volumes:
  #     - ./config/valkey.conf:/etc/valkey/valkey.conf
  #     # - fso-cache-data:/data
  #   command: valkey-server /etc/valkey/valkey.conf
  #   ports:
  #     - 6380:6379
  # query-cache:
  #   container_name: fso-query-cache
  #   hostname: valkey
  #   image: valkey/valkey:7.2.5
  #   volumes:
  #     - ./config/valkey.conf:/etc/valkey/valkey.conf
  #     # - fso-cache-data:/data
  #   command: valkey-server /etc/valkey/valkey.conf
  #   ports:
  #     - 6381:6379

volumes:
  fso-db-data: # TODO rename to fso-card-db-data
  time-db-data: