PlayerCount: 2
CoinPool: 100
InitialTreasureSlots: 2
InitialMonsterSlots: 2
InitialRoomSlots: 2
BonusSoulCount: 3
InitialDealLoot: 3
InitialDealCoins: 3
SoulsToWin: 4
ForceInclude3PlusCards: yes
RandomFirstPlayer: yes
MaxHandSize: 10
StrictMode: yes
PurchaseCountDefault: 1
AttackCountDefault: 1
LootStepLootAmount: 1
LootPlay: 10 # TODO change to 1
LootCards:
  3-cents-v2: 60
  a-sack-v2: 60
Characters:
  - guppy-v2
StartingItems:
  - infestation-v2