MaxPlayerCount: 4
CoinPool: 100
InitialTreasureSlots: 2
InitialMonsterSlots: 2
InitialRoomSlots: 2
BonusSoulCount: 3
InitialDealLoot: 3
InitialDealCoins: 3
SoulsToWin: 4
ForceInclude3PlusCards: yes
RandomFirstPlayer: yes
MaxHandSize: 10
StrictMode: no
PurchaseCountDefault: 1
AttackCountDefault: 1
LootStepLootAmount: 1

LootPlay: 1
# LootPlay: 100

LootCards:
  3-cents-v2: 10
  a-sack-v2: 10
  counterfeit-penny-v2: 10
  orange-green-pills-v2: 100
  chunk-of-amber-warp: 10
  xvii-the-stars-v2: 10
  dice-shard-v2: 100
Treasures:
  # - mystery-sack-v2
  # - portable-slot-machine-v2
  # - the-butter-bean-v2
  # - pageant-boy-v2
  # - box-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  - crooked-penny-v2
  # - box-v2
Characters:
  - guppy-v2
  - the-keeper-v2
  - isaac-v2
StartingItems:
  - infestation-v2
  - wooden-nickel-v2
  - the-d6-v2