MaxPlayerCount: 4
CoinPool: 100
InitialTreasureSlots: 2
InitialMonsterSlots: 2
InitialRoomSlots: 2
BonusSoulCount: 3
InitialDealLoot: 3
InitialDealCoins: 3
SoulsToWin: 4
ForceInclude3PlusCards: yes
RandomFirstPlayer: yes
MaxHandSize: 10
StrictMode: no
PurchaseCountDefault: 1
AttackCountDefault: 1
LootStepLootAmount: 1
# LootPlay: 1
LootPlay: 100
LootCards:
  # 3-cents-v2: 60
  # a-sack-v2: 60
  counterfeit-penny-v2: 60
Characters:
  - guppy-v2
StartingItems:
  - infestation-v2