MaxPlayerCount: 4
CoinPool: 100
InitialTreasureSlots: 2
InitialMonsterSlots: 2
InitialRoomSlots: 2
BonusSoulCount: 3
InitialDealLoot: 3
InitialDealCoins: 3
SoulsToWin: 4
ForceInclude3PlusCards: yes
RandomFirstPlayer: yes
MaxHandSize: 10
StrictMode: no
PurchaseCountDefault: 1
AttackCountDefault: 1
LootStepLootAmount: 1
CharactersStartTapped: yes
PurchaseCost: 10

LootPlay: 1
# LootPlay: 100

LootCards:
  3-cents-v2: 10
  a-sack-v2: 10
  counterfeit-penny-v2: 10
  orange-green-pills-v2: 10
  chunk-of-amber-warp: 10
  xvii-the-stars-v2: 10
  dice-shard-v2: 10
  lil-battery-v2: 10
  lucky-toe-requiem: 10
  xvii-the-stars-alt1: 10
Treasures:
  - mystery-sack-v2
  - portable-slot-machine-v2
  - the-butter-bean-v2
  - pageant-boy-v2
  - box-v2
  - crooked-penny-v2
  - the-battery-v2
  - the-d20-v2
  - pay-to-play-v2
  - libra-v2
  - dads-lost-coin-v2
  - sacred-heart-v2
  - moms-purse-v2
  - the-relic-v2
  - eye-of-greed-v2
  - guppys-eye-v2
  - shiny-rock-v2
  - guppys-tail-v2
  - hourglass-v2
  - trinity-shield-v2
  - restock-v2
  - a-dollar-uoi
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
  # - eye-of-greed-v2
Characters:
  - guppy-v2
  - the-keeper-v2
  - isaac-v2
  - judas-v2
  - the-miser-requiem
StartingItems:
  - infestation-v2
  - wooden-nickel-v2
  - book-of-belial-v2
  - the-d6-v2
  - keepers-bargain-requiem