MaxPlayerCount: 4
CoinPool: 100
InitialTreasureSlots: 2
InitialMonsterSlots: 2
InitialRoomSlots: 2
BonusSoulCount: 3
InitialDealLoot: 3
InitialDealCoins: 3
SoulsToWin: 4
ForceInclude3PlusCards: yes
RandomFirstPlayer: yes
MaxHandSize: 10
StrictMode: no
PurchaseCountDefault: 1
AttackCountDefault: 1
LootStepLootAmount: 1
CharactersStartTapped: yes
PurchaseCost: 10
DeathPenaltyLoot: 1
DeathPenaltyCoins: 1
DeathPenaltyItems: 1

LootPlay: 1

LootCards:
  3-cents-b2: 10
  a-sack-b2: 10
  counterfeit-penny-b2: 10
  pills-orange-green-b2: 10
  chunk-of-amber-warp: 10
  xvii-the-stars-b2: 10
  dice-shard-b2: 10
  lil-battery-b2: 10
  lucky-toe-r: 10
  xvii-the-stars-alt1: 10
  lost-soul-b2: 100
  perthro-r: 10
  bag-lunch-r: 10
  blank-rune-b2: 10
  bloody-penny-b2: 10
  bible-thump-r: 10
  xiii-death-b2: 10
  x-wheel-of-fortune-b2: 10
  xiv-temperance-b2: 10
  butter-bean-b2: 10
Treasures:
  - keepers-box-r
  - portable-slot-machine-b2
  - the-butter-bean-b2
  - pageant-boy-b2
  - box-b2
  - crooked-penny-b2
  - the-battery-b2
  - the-d20-b2
  - pay-to-play-b2
  - libra-b2
  - dads-lost-coin-b2
  - sacred-heart-b2
  - moms-purse-b2
  - the-relic-b2
  - eye-of-greed-b2
  - guppys-eye-b2
  - shiny-rock-b2
  - guppys-tail-b2
  - hourglass-b2
  - trinity-shield-b2
  - restock-b2
  - a-dollar-uoi
  - godhead-b2
  - a-friend-summer
  - the-chest-b2
  - jawbone-b2
  - guppys-head-b2
  - chaos-b2
  - breakfast-b2
  - belly-button-b2
  - dark-bum-b2
  - fanny-pack-b2
  - experimental-treatment-r
  - moms-razor-b2
  - shadow-b2
  - razor-blade-b2
  - the-habit-b2
Characters:
  - bum-bo-b2
  - guppy-b2
  - the-keeper-b2
  - isaac-b2
  - judas-b2
  - the-miser-r
  - the-empty-r
  - dark-judas-b2
  - lazarus-b2
  - the-dauntless-r
  - the-baleful-r
  - the-hoarder-r
StartingItems:
  - hypercoagulation-r
  - infestation-b2
  - wooden-nickel-b2
  - book-of-belial-b2
  - the-d6-b2
  - keepers-bargain-r
  - abyss-r
  - dark-arts-b2
  - lazarus-rags-b2
  - soulbond-r
  - bag-o-trash-b2
  - bag-of-crafting-r
BonusSouls:
  - soul-of-greed-b2
  - soul-of-gluttony-b2
  - soul-of-guppy-b2
  - strawberry-warp