#!/bin/python3

from sys import argv

import fscommon as fs

INSERT_RELATION_FORMAT = 'INSERT INTO "CardRelations"("RelatedToKey", "RelatedCardKey", "RelationType") VALUES (\'{card_key}\', \'{related_card_key}\', {relation_type});\n'

class RelationTypes:
    StartingItem = 1

if len(argv) != 3:
    print('Invalid amount of arguments')
    exit(1)

cards_collection_path = argv[1]
out_path = argv[2]

cards: fs.CardCollection = fs.CardCollection.load_from_dir(cards_collection_path)

result = ''

# starting items
characters = cards.get_characters()
for character in characters:
    starting_items = character.extract_starting_items()
    for item in starting_items:
        result += INSERT_RELATION_FORMAT.format_map({
            'card_key': character.key,
            'related_card_key': item.key,
            'relation_type': RelationTypes.StartingItem
        })

open(out_path, 'w').write(result)